# Generated by Django 6.0.5 on 2026-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Baja', '🟢 Baja'), ('Media', '🟡 Media'), ('Alta', '🔴 Alta')], default='Baja', max_length=10),
        ),
    ]
