# Generated by Django 6.0.5 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_priority_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
