# Generated by Django 6.0.5 on 2026-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('progreso', '🔄 En Progreso'), ('completada', '✅ Completada')], default='pendiente', max_length=15),
        ),
    ]
