# Generated by Django 6.0.5 on 2026-06-05 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknote',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificada'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificada'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificada'),
        ),
        migrations.AddField(
            model_name='tag',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificada'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasknote',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificada'),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
