# Generated by Django 6.0.5 on 2026-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_tasknote_created_at_project_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
